### ISSUE TITLE
Guards in prefabs do not adjust appearance according to corporation

### ISSUE THREAD

**Issue by Mobbstar** [Mobbstar/InvisibleInc-MoreMissions#1]
For example, the NPC Guard in Assassination offices (supposed to represent a bodyguard). Despite being functionally identical, the anim does not change depending on the territory.

I propose either the template becomes sensitive to this, or a corp-independent design for these gets introduced (akin to Captains).

**Comment by Hekateras** [comment]
Closed as we use unique guards for this anyway.
