### ISSUE TITLE
bug: program slot didnt upgrade in AI terminal from 5 to 6

### ISSUE THREAD

**Issue by voidicet** [Mobbstar/InvisibleInc-MoreMissions#102]
program slot not having upgrade in AI terminal from 5 to 6 , custom endless , 3rd day , second AI terminal

gear shift , upgraded bribe , "bead counter" , lighting , wisp 

save : https://easyupload.io/q0iyzw

mod :

Expanded Cheats
Agent Reserve
Urist (from Dwarf Fortress)
Augment Drill Return
Dull - little sister of Sharp
Unlimited Storage
Worldgen Extended
Cover overlays for agent mods
Neptune Corporation
Function Library
Agent 47
PEIA Legends: On-File Draco & Rush
Improvisation Items
Quick Loader
Agent: Schysm
New Corporate Tactics
Agent Wilson (from Don't Starve)
UI Tweaks
Sim Constructor + Sequential Mod Loader
New Items and Augments
Agent Mods Combo
Talon Recruitment (Overwatch Agents) [v7]
Advanced Guard Protocol
Programs Extended
Talkative Agents (+ Chatty Guards)
Agent Mod - Carmen Sandiego
Red (from Transistor)
Additional Banter
Archive Mod Agents

**Comment by Hekateras** [comment]
Did you exit the mission? The new slot only shows up in the next mission. The effect is not immediate.

**Comment by voidicet** [comment]
> Did you exit the mission? The new slot only shows up in the next mission. The effect is not immediate.

Yea pal , I only notice on next level server farm ........ I can play a bit on my 2nd day backup save if you need

**Comment by Hekateras** [comment]
Haven't been able to reproduce the bug so far. I'd like to look at your save, but for that I'll need you to upload the contents of your Mods folder somewhere, as well.

If you want to take a look yourself, the relevant code is in missions/ai_terminal.lua, starting with line 758. After the mission is done, sim:getParams().agency.W93_aiTerminals table should have a value of 1. The code that actually handles the slot addition is in Function Library, though.

But I suggest you upload your Mods so I can get to the bottom of this myself. There's a high chance this is some kind of mod conflict (since the slot upgrade thing hasn't been touched in ages and should work fine, so nothing should have broken on our end.)

**Comment by voidicet** [comment]
ok here s the mods , save backup and the save where I notice it

https://drive.google.com/file/d/10XUGdW2mPDHkpIhrMhshIsAYv510qmma/view?usp=sharing

**Comment by Hekateras** [comment]
Hm, so. I loaded up the fourth slot (which was a Detention Center mission, I assume this is the correct slot), left the mission, then went to a Plastech AI Terminal and got the upgrade. Upgrade showed up with no issue the next mission.

**Comment by Hekateras** [comment]
On an unrelated note, you need to update PE, some of your save slots are crashing on load and it's a PE thing

**Comment by voidicet** [comment]
> Hm, so. I loaded up the fourth slot (which was a Detention Center mission, I assume this is the correct slot), left the mission, then went to a Plastech AI Terminal and got the upgrade. Upgrade showed up with no issue the next mission.

ok I will play it out to the next Plastech

**Comment by Hekateras** [comment]
Corp really shouldn't matter. But yeah, let me know if your next attempt at a slot upgrade works or not.

**Comment by Hekateras** [comment]
May have a lead on the 'upgrade not carrying over' bug.

Do you remember if you used Retry Level in AI Terminal?

**Comment by Hekateras** [comment]
Fixed
https://github.com/Mobbstar/InvisibleInc-MoreMissions/pull/127

**Comment by Hekateras** [comment]
Fixed
https://github.com/Mobbstar/InvisibleInc-MoreMissions/pull/127
