### ISSUE TITLE
Stationary Guards from prefabs don't remember their facing direction

### ISSUE THREAD

**Issue by Mobbstar** [Mobbstar/InvisibleInc-MoreMissions#2]
simunit.createUnit() applies facing once, directly, but never through patrol points, even if defined by the prefab in the luaData for that patrol.

I believe "hacking into the simfactory" (as done a few times in the Transistor mod) would let us fix this issue rather quickly, but there may be a more elegant solution.

**Comment by Hekateras** [comment]
closing because i'm pretty sure this isn't relevant anymore
