### ISSUE TITLE
AI Terminal: should list the available upgrade categories earlier

### ISSUE THREAD

**Issue by qoala** [Mobbstar/InvisibleInc-MoreMissions#43]
Current flow for applying an upgrade is:

1. slot or upgrade? (choose upgrade)
2. which program? (choose 1 of your programs)
3. which upgrade type? (choose 1 of the available upgrade types)
4. increase or decrease? (choose from increase/decrease/restart)

Because only some upgrade types are available each mission, it would help if the available upgrade types were listed on at least step 2 (so that an experienced player doesn't have to pick a potentially inapplicable program just to figure out which upgrade types are available).

Suggestions:

* List "Available Upgrade Categories: A, B" as an info line in both steps 1 and 2, for experienced players
* "Start Over" option is available on all screens, not just the final screen in a chain. (so that players unfamiliar with the mod aren't scared to pick options)

**Comment by Hekateras** [comment]
Fixed with the second option: Start Over available on most screens except for the program selection screen (for UI space reasons)
