### ISSUE TITLE
Informant: 3rd full-success Central line uses similar phrasing to partial success

### ISSUE THREAD

**Issue by qoala** [Mobbstar/InvisibleInc-MoreMissions#46]
> Well done, Operator. With that informant in place, our job will be that much easier. Pity we won't have access to that intel for long.

The with-witnesses lines all use similar "not [available] for long" phrasing, which made the above central judgement confusing. I thought she'd given me a partial success.

> You weren't supposed to leave witnesses. Our mole on the inside won't be able to feed us intel for long before their cover is blown. Still, it's better than nothing.  
>  
> Next time, try to make sure the mole is unseen. They'll be useful to us for that much longer if their cover is secure.  
>  
> A job half done. We won't be able to use their intel for long, not with the witnesses you left behind. Be more careful next time.

**Comment by Hekateras** [comment]
fixed
