### ISSUE TITLE
HowTo (non-issue): Creating a custom floor grid

### ISSUE THREAD

**Issue by qoala** [Mobbstar/InvisibleInc-MoreMissions#47]
Creating this as an issue because I blew past discord's character limit.

In vanilla, see `boardrig` and `cellrig`. In Backstab, see [boardrig](https://github.com/qoala/InvisibleInc-BattleRoyale/blob/master/scripts/boardrig.lua) and [cellrig](https://github.com/qoala/InvisibleInc-BattleRoyale/blob/master/scripts/cellrig.lua) appends.

---

* Add an append to `boardrig:init` that calls a new `createFooGridProp`
  * attach the new grid prop to `self._layers["floor"]`
  * and save a reference to the grid prop on the boardrig, for updates and the destructor
* Add an append to `boardrig:destroy`
  * `self._layers["floor"]:removeProp(self._whateverYouCalledTheNewGridProp)`
  * This must run _before_ you call `oldDestroy`. (Otherwise the reference will already be lost)

* Creating the grid prop:
  * Backstab makes a double-size grid (each tile is composed of 4 corners), so the vanilla `createGridProp` might be a better starting point.
  * The `params` argument to the vanilla grid is always `cdefs.LEVELTILES_PARAMS`. You might be able to reuse the exact same params if you only need a black tile.
  * Create a `MOAIGrid` and call `initRectGrid` with the vanilla arguments
  * Create and configure a `MOAITileDeck2D`
    * If you want the LOS shader to apply to this grid, you likely need to configure the same `MOAIMultiTexture` as the vanilla grid.
    * Otherwise, just `setTexture` with the tiles file. This is what `createBackstabGridProp` does
    * Regardless `setSize`, `setRect`, & `setUVRect` from the `params`. These 3 lines are the same between `createBackstabGridProp` and vanilla `createGridProp`
  * Create and configure a `MOAIProp2D`
    * Attach the tile deck and grid to the prop.
    * You don't need the fade animation, so no need for the Remapper in `createBackstabGridProp`
    * vanilla args to `:setLoc` and `:setDepthTest`
    * To draw beneath the normal tiles, `setPriority( cdefs.BOARD_PRIORITY - 10 )` or similar (lower priority than the vanilla board)
  * `prop:forceUpdate()` before it's returned
* Setting the tiles to black:
  * vanilla grid sets the tiles in `cellrig:refresh`. Backstab sets its tiles in `cellrig:backstab_refreshOverlay`, called from `:refresh` and manually on updates.
    * If you want the tiles to appear conditionally, tying to the cellrig might fit. Otherwise you could just iterate over all x and y values in the grid.
  * `_newGridProp:getGrid():setTile( x, y, tileIndex )` tells the prop which tile from the tilemap textrue to draw in that space.
    * `cdefs.BLACKOUT_CELL` already exists with a pure-black tile in the correct size, if you use the normal tile grid's `leveltiles.png`.
  * `_newGridProp:getGrid():setTileFlags( x, y, flags )` controls how that tile is drawn. You likely only need 2 values:
    * `0` draws the tile normally
    * `MOAIGridSpace.TILE_HIDE` results in nothing drawn for this tile.

**Comment by Hekateras** [comment]
Note: This is not an issue with More Missions, just some useful code for elsewhere (may or may not come in handy for MM)

**Comment by qoala** [comment]
Closing to remove from active issues list
