### ISSUE TITLE
Informant can't pick cloak back up

### ISSUE THREAD

**Issue by Hekateras** [Mobbstar/InvisibleInc-MoreMissions#56]
The informant's cloak can only be carried by the informant. Normally you cannot drop it, but it's possible to transfer it to an existing stack of items on the floor. You can't pick it up again after that.

This is a vanilla bug which would normally only happen with Central and Incognita's drive, but we still need to fix it. (Maybe something for Sim Constructor or CBF instead?)

**Comment by qoala** [comment]
CBF fixes the bug with Incognita's drive generally based on the `pickupOnly` trait, so should also apply here.

The fix is in [`items_panel.lua`](https://github.com/qoala/InvisibleInc-CommunityBugFixes/blob/master/scripts/items_panel.lua) if you want to copy it.

**Comment by Hekateras** [comment]
Fixed by CBF/CBF added as prerequisite
