### ISSUE TITLE
bugs: AI terminal UI issues

### ISSUE THREAD

**Issue by kalecgos13** [Mobbstar/InvisibleInc-MoreMissions#99]
Hello,

So I noticed these two bugs on version 0.22.0:

1. There is a weird UI button in the center that does not do anything:
![20220116193200_1](https://user-images.githubusercontent.com/38404765/149673153-e09bb9a6-588a-4330-bf77-98111ecd4f27.jpg)

2. When you have no available programs to upgrade (when they are all already upgraded for instance) and you click on the "upgrade program" button, then you see no available program. But the thing is, you cannot go back or exit this screen, meaning you are stuck in this screen:
![20220116193203_1](https://user-images.githubusercontent.com/38404765/149673175-63611599-9253-48f9-b115-4bad57d75976.jpg)

**Comment by Hekateras** [comment]
Just to be on the safe side, did you update Sim Constructor mod?

**Comment by Hekateras** [comment]
Assuming you've updated, can you confirm that the issue with the weird empty button still happens with a fresh campaign? (you can back up your save if you don't have any empty slots and delete one)

**Comment by Hekateras** [comment]
Upload the log, please. I have a suspicion this is a compatibility issue with Interactive Events.

**Comment by kalecgos13** [comment]
Here is the log file of it happening: [invisibleinc.txt](https://github.com/Mobbstar/InvisibleInc-MoreMissions/files/7884532/invisibleinc.txt)

I did refresh the mods and updated the mods and this is a new campaign

**Comment by Hekateras** [comment]
It does look like the empty button is an IE conflict, but it needs to be fixed on the IE end. Keep an eye out for an update to IE. (If you're curious, the reason for the issue now is that IE and MM both make the same change to the choice dialog screen to allow multiple response options, and MM recently switched to using the new screen editing API from Sim Constructor to make the change while IE hasn't. Using the API is good for mod compatibility in the long run, but first, mods need to switch over to it...)


As for the other thing... I have a hunch why that happens, might be another artefact of The Great Cleanup.

**Comment by Hekateras** [comment]
Yeah, found and fixed the incorrect mission weighting. Will be out in the next update.

**Comment by Hekateras** [comment]
Update with fixed mission weighting is out: https://github.com/Mobbstar/InvisibleInc-MoreMissions/releases/tag/alphaV0.22.1
For the other thing, as said, wait for an IE update, but at least the empty button seems harmless.
